theme: jekyll-theme-modernist
show_downloads: true

# google_analytics:[Your Google Analytics tracking ID]

# Name of website
title: Image Super sampling using pixel subsampling
description: Project for UCLA ECEM202A/CSM213A (Fall 2021)
